name: ClaudeUsage
options:
  bundleIdPrefix: com.azimi
  deploymentTarget:
    macOS: "14.0"
  xcodeVersion: "16.0"
  generateEmptyDirectories: true
settings:
  base:
    SWIFT_VERSION: "5.10"
    MACOSX_DEPLOYMENT_TARGET: "14.0"
targets:
  ClaudeUsage:
    type: application
    platform: macOS
    sources:
      - Sources
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.azimi.claude-usage
        INFOPLIST_FILE: Resources/Info.plist
        CODE_SIGN_ENTITLEMENTS: Resources/ClaudeUsage.entitlements
        CODE_SIGN_STYLE: Automatic
        LD_RUNPATH_SEARCH_PATHS:
          - "@executable_path/../Frameworks"
